version: '3.7'
services:
  postgres:
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    volumes:
      - pgadmin:/var/lib/pgadmin
  charon:
    image: charon:dev
    build:
      args:
        NODE_ENV: development
    command: nodemon -L
    environment:
      NODE_ENV: development
    volumes:
      - ./charon/src:/usr/app/src
      - ./node_modules:/usr/app/src/node_modules
volumes:
  postgres:
  pgadmin: